#include <psp2/ctrl.h>
#include <psp2/appmgr.h>
#include <psp2/io/fcntl.h>
#include <psp2/io/stat.h>
#include <psp2/kernel/processmgr.h>
#include <psp2/kernel/threadmgr.h>
#include <psp2/gxm.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vitaGL.h>

#include "data_win.h"
#include "gl_legacy_renderer.h"
#include "noop_audio_system.h"
#include "overlay_file_system.h"
#include "runner.h"
#include "runner_gamepad.h"
#include "runner_keyboard.h"
#include "vm.h"

#define DATA_ROOT "ux0:data/deltarune/butterscotch/"
#define SAVE_PATH "ux0:data/deltarune/save/"
#define LOG_PATH DATA_ROOT "butterscotch-probe.log"
#define NEXT_CHAPTER_PATH DATA_ROOT "next-chapter.txt"

// The Vita defaults the main thread to a 256 KiB stack. The first fixed-pipeline
// shader generated by vitaGL/ShaccCg needs substantially more and corrupted the
// return stack before the first draw. Keep this symbol global: the Vita runtime
// reads it while creating the main thread.
unsigned int sceUserMainThreadStackSize = 4 * 1024 * 1024;

typedef struct { uint32_t mask; int key; } KeyMap;
static const KeyMap KEY_MAP[] = {
    {SCE_CTRL_UP, VK_UP}, {SCE_CTRL_DOWN, VK_DOWN},
    {SCE_CTRL_LEFT, VK_LEFT}, {SCE_CTRL_RIGHT, VK_RIGHT},
    {SCE_CTRL_CROSS, 'Z'}, {SCE_CTRL_CIRCLE, 'Z'},
    {SCE_CTRL_SQUARE, 'X'}, {SCE_CTRL_TRIANGLE, 'C'},
    {SCE_CTRL_START, 'C'}, {SCE_CTRL_LTRIGGER, VK_PAGEDOWN},
    {SCE_CTRL_RTRIGGER, VK_PAGEUP}
};

static void log_line(const char *text) {
    SceUID fd = sceIoOpen(LOG_PATH, SCE_O_WRONLY | SCE_O_CREAT | SCE_O_APPEND, 0666);
    if (fd >= 0) {
        sceIoWrite(fd, text, strlen(text));
        sceIoWrite(fd, "\n", 1);
        sceIoClose(fd);
    }
}

static void progress(const char *chunk, int index, int total, DataWin *dw, void *user) {
    (void)dw; (void)user;
    char line[96];
    snprintf(line, sizeof(line), "LOAD chunk=%.4s %d/%d", chunk, index + 1, total);
    log_line(line);
    sceKernelDelayThread(1000);
}

static void set_key(RunnerKeyboardState *kb, int key, bool down, bool *previous) {
    if (down && !*previous) RunnerKeyboard_onKeyDown(kb, key);
    else if (!down && *previous) RunnerKeyboard_onKeyUp(kb, key);
    *previous = down;
}

static int consume_next_chapter(void) {
    char value = '0';
    SceUID fd = sceIoOpen(NEXT_CHAPTER_PATH, SCE_O_RDONLY, 0);
    if (fd >= 0) {
        sceIoRead(fd, &value, 1);
        sceIoClose(fd);
        sceIoRemove(NEXT_CHAPTER_PATH);
    }
    return value >= '0' && value <= '5' ? value - '0' : 0;
}

static bool restart_into_chapter(int chapter) {
    if (chapter < 0 || chapter > 5) return false;
    char value = (char) ('0' + chapter);
    SceUID fd = sceIoOpen(NEXT_CHAPTER_PATH, SCE_O_WRONLY | SCE_O_CREAT | SCE_O_TRUNC, 0666);
    if (fd < 0) return false;
    bool written = sceIoWrite(fd, &value, 1) == 1;
    sceIoClose(fd);
    if (!written) return false;
    char line[80];
    snprintf(line, sizeof(line), "GAME_CHANGE=restart chapter=%d", chapter);
    log_line(line);
    int result = sceAppMgrLoadExec("app0:eboot.bin", NULL, NULL);
    snprintf(line, sizeof(line), "GAME_CHANGE=loadexec_returned result=0x%08X", result);
    log_line(line);
    return result >= 0;
}

static int chapter_from_request(const char *working_directory) {
    if (working_directory == NULL) return -1;
    const char *chapter = strstr(working_directory, "chapter");
    if (chapter == NULL) return -1;
    chapter += strlen("chapter");
    return chapter[0] >= '0' && chapter[0] <= '5' ? chapter[0] - '0' : -1;
}

int main(void) {
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);
    sceIoMkdir("ux0:data/deltarune", 0777);
    sceIoMkdir(DATA_ROOT, 0777);
    sceIoMkdir(SAVE_PATH, 0777);
    sceIoRemove(LOG_PATH);
    int active_chapter = consume_next_chapter();
    char game_path[128];
    char bundle_path[128];
    snprintf(game_path, sizeof(game_path), DATA_ROOT "chapter%d/game.droid", active_chapter);
    snprintf(bundle_path, sizeof(bundle_path), DATA_ROOT "chapter%d/", active_chapter);

    log_line("Deltarune Butterscotch VitaRenderer runner 00.18");
    log_line("MAIN_STACK=4194304");
    char startup_line[96];
    snprintf(startup_line, sizeof(startup_line), "AUDIO=noop ENTRY=chapter%d CONTROLS=vita", active_chapter);
    log_line(startup_line);

    sceCtrlSetSamplingMode(SCE_CTRL_MODE_ANALOG);
    // The generated fixed-pipeline shader used by the legacy renderer trips the
    // aggressive runtime optimizer on Vita. O0 is slower only during the first
    // compilation and avoids that optimizer path entirely.
    vglSetupRuntimeShaderCompiler(SHARK_OPT_SLOW, 0, 0, 0);
    log_line("SHARK=opt_slow fastmath=0 fastprecision=0 fastint=0");
    log_line("RENDERER=vita_arrays_v2 immediate_bridge=all STDIO=unbuffered");
    log_line("VITAGL=init_begin reserve=67108864");
    vglInitExtended(0, 960, 544, 64 * 1024 * 1024, SCE_GXM_MULTISAMPLE_NONE);
    log_line("VITAGL=init_complete");

    DataWinParserOptions options = {0};
    options.parseGen8 = true; options.parseOptn = true; options.parseLang = true;
    options.parseExtn = true; options.parseSond = true; options.parseAgrp = true;
    options.parseSprt = true; options.parseBgnd = true; options.parsePath = true;
    options.parseScpt = true; options.parseGlob = true; options.parseShdr = true;
    options.parseFont = true; options.parseTmln = true; options.parseObjt = true;
    options.parseRoom = true; options.parseTpag = true; options.parseCode = true;
    options.parseVari = true; options.parseFunc = true; options.parseStrg = true;
    options.parseTxtr = true; options.parseAudo = false;
    options.skipLoadingPreciseMasksForNonPreciseSprites = true;
    options.lazyLoadRooms = true;
    options.lazyLoadTextures = true;
    options.loadType = DATAWINLOADTYPE_LOAD_PER_CHUNK;
    options.progressCallback = progress;

    log_line("DATAWIN=parse_begin");
    DataWin *dw = DataWin_parse(game_path, options);
    log_line("DATAWIN=parse_complete");
    VMContext *vm = VM_create(dw);
    log_line("VM=create_complete");
    OverlayFileSystem *fs = OverlayFileSystem_create(bundle_path, SAVE_PATH);
    Renderer *renderer = GLLegacyRenderer_create();
    AudioSystem *audio = (AudioSystem *)NoopAudioSystem_create();
    log_line("SUBSYSTEMS=create_complete");

    Runner *runner = Runner_create(dw, vm, renderer, (FileSystem *)fs, audio);
    char *game_args[] = {"eboot.bin", "-game", "data.win"};
    Runner_setGameArgs(runner, game_args, 3);
    runner->debugMode = false;
    log_line("RUNNER=create_complete");
    Runner_initFirstRoom(runner);
    log_line("RUNNER=first_room_complete");

    bool previous[sizeof(KEY_MAP) / sizeof(KEY_MAP[0])] = {0};
    bool stick_previous[4] = {0};
    uint32_t frame = 0;
    uint64_t last_time = sceKernelGetProcessTimeWide();
    bool exit_requested = false;

    while (!exit_requested && !runner->shouldExit) {
        RunnerKeyboard_beginFrame(runner->keyboard);
        RunnerGamepad_beginFrame(runner->gamepads);
        SceCtrlData pad = {0};
        sceCtrlPeekBufferPositive(0, &pad, 1);
        for (unsigned i = 0; i < sizeof(KEY_MAP) / sizeof(KEY_MAP[0]); ++i)
            set_key(runner->keyboard, KEY_MAP[i].key, (pad.buttons & KEY_MAP[i].mask) != 0, &previous[i]);

        int dx = (int)pad.lx - 128, dy = (int)pad.ly - 128;
        set_key(runner->keyboard, VK_LEFT, dx < -48, &stick_previous[0]);
        set_key(runner->keyboard, VK_RIGHT, dx > 48, &stick_previous[1]);
        set_key(runner->keyboard, VK_UP, dy < -48, &stick_previous[2]);
        set_key(runner->keyboard, VK_DOWN, dy > 48, &stick_previous[3]);
        if (pad.buttons & SCE_CTRL_SELECT) exit_requested = true;

        uint64_t now = sceKernelGetProcessTimeWide();
        runner->deltaTime = (double)(now - last_time);
        last_time = now;
        if (frame == 0) log_line("FRAME0=step_begin");
        Runner_step(runner);
        if (frame == 0) log_line("FRAME0=step_complete");
        if (runner->pendingWorkingDirectory != NULL) {
            int requested_chapter = chapter_from_request(runner->pendingWorkingDirectory);
            char line[160];
            snprintf(line, sizeof(line), "GAME_CHANGE=request cwd=%s params=%s parsed=%d",
                     runner->pendingWorkingDirectory,
                     runner->pendingLaunchParameters ? runner->pendingLaunchParameters : "<null>",
                     requested_chapter);
            log_line(line);
            if (restart_into_chapter(requested_chapter)) {
                sceKernelDelayThread(500000);
                sceKernelExitProcess(0);
            }
            log_line("GAME_CHANGE=restart_failed");
            exit_requested = true;
            continue;
        }
        runner->audioSystem->vtable->update(runner->audioSystem, (float)(runner->deltaTime / 1000000.0));

        glClearColor(0, 0, 0, 1);
        glClear(GL_COLOR_BUFFER_BIT);
        int game_w = (int)dw->gen8.defaultWindowWidth;
        int game_h = (int)dw->gen8.defaultWindowHeight;
        if (frame == 0) log_line("FRAME0=draw_pre_begin");
        Runner_drawPre(runner, 960, 544);
        if (frame == 0) log_line("FRAME0=draw_pre_complete");
        Runner_beginFrame(runner, game_w, game_h, 960, 544, 960, 544);
        if (frame == 0) log_line("FRAME0=begin_frame_complete");
        Runner_drawViews(runner, game_w, game_h, false);
        if (frame == 0) log_line("FRAME0=draw_views_complete");
        renderer->vtable->endFrameInit(renderer);
        Runner_drawPost(runner, 960, 544);
        renderer->vtable->endFrameEnd(renderer);
        Runner_drawGUI(runner, 960, 544, game_w, game_h);
        if (runner->pendingRoom == -1) vglSwapBuffers(GL_FALSE);
        Runner_handlePendingRoomChange(runner);

        frame++;
        if (frame == 1) log_line("FRAME=first_complete");
        if (frame == 60) log_line("FRAME=60_complete");
        int speed = runner->currentRoom && runner->currentRoom->speed ? (int)runner->currentRoom->speed : 30;
        sceKernelDelayThread((unsigned int)(1000000 / speed));
    }

    log_line(exit_requested ? "EXIT=select_pressed" : "EXIT=runner_requested");
    runner->audioSystem->vtable->destroy(runner->audioSystem);
    renderer->vtable->destroy(renderer);
    Runner_free(runner);
    OverlayFileSystem_destroy(fs);
    VM_free(vm);
    DataWin_free(dw);
    log_line("PROCESS=exit_clean");
    sceKernelExitProcess(0);
    return 0;
}
