#include <psp2/ctrl.h>
#include <psp2/appmgr.h>
#include <psp2/io/fcntl.h>
#include <psp2/io/stat.h>
#include <psp2/kernel/processmgr.h>
#include <psp2/kernel/threadmgr.h>
#include <psp2/gxm.h>
#include <psp2/touch.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vitaGL.h>

#include "data_win.h"
#include "gl_legacy_renderer.h"
#include "audio/openal/al_audio_system.h"
#include "overlay_file_system.h"
#include "runner.h"
#include "runner_gamepad.h"
#include "runner_keyboard.h"
#include "runner_mouse.h"
#include "vita_settings.h"
#include "vita_borders.h"
#include "vm.h"

#define DATA_ROOT "ux0:data/deltarune/deltarunevita/"
#define SAVE_PATH "ux0:data/deltarune/save/"
#define LOG_PATH DATA_ROOT "butterscotch-probe.log"
#define NEXT_CHAPTER_PATH DATA_ROOT "next-chapter.txt"

// The Vita defaults the main thread to a 256 KiB stack. The first fixed-pipeline
// shader generated by vitaGL/ShaccCg needs substantially more and corrupted the
// return stack before the first draw. Keep this symbol global: the Vita runtime
// reads it while creating the main thread.
unsigned int sceUserMainThreadStackSize = 4 * 1024 * 1024;

typedef struct { uint32_t mask; int key; } KeyMap;
static const KeyMap KEY_MAP[] = {
    {SCE_CTRL_UP, VK_UP}, {SCE_CTRL_DOWN, VK_DOWN},
    {SCE_CTRL_LEFT, VK_LEFT}, {SCE_CTRL_RIGHT, VK_RIGHT},
    {SCE_CTRL_CROSS, 'Z'}, {SCE_CTRL_CIRCLE, 'X'},
    {SCE_CTRL_SQUARE, 'X'}, {SCE_CTRL_TRIANGLE, 'C'},
    {SCE_CTRL_LTRIGGER, VK_PAGEDOWN},
    {SCE_CTRL_RTRIGGER, VK_PAGEUP}
};

static void log_line(const char *text) {
    SceUID fd = sceIoOpen(LOG_PATH, SCE_O_WRONLY | SCE_O_CREAT | SCE_O_APPEND, 0666);
    if (fd >= 0) {
        sceIoWrite(fd, text, strlen(text));
        sceIoWrite(fd, "\n", 1);
        sceIoClose(fd);
    }
}

static void progress(const char *chunk, int index, int total, DataWin *dw, void *user) {
    (void)dw; (void)user;
    char line[96];
    snprintf(line, sizeof(line), "LOAD chunk=%.4s %d/%d", chunk, index + 1, total);
    log_line(line);
    sceKernelDelayThread(1000);
}

static void set_key(RunnerKeyboardState *kb, int key, bool down, bool *previous) {
    if (down && !*previous) RunnerKeyboard_onKeyDown(kb, key);
    else if (!down && *previous) RunnerKeyboard_onKeyUp(kb, key);
    *previous = down;
}

static int consume_next_chapter(void) {
    char value = '0';
    SceUID fd = sceIoOpen(NEXT_CHAPTER_PATH, SCE_O_RDONLY, 0);
    if (fd >= 0) {
        sceIoRead(fd, &value, 1);
        sceIoClose(fd);
        sceIoRemove(NEXT_CHAPTER_PATH);
    }
    return value >= '0' && value <= '5' ? value - '0' : 0;
}

static bool restart_into_chapter(int chapter) {
    if (chapter < 0 || chapter > 5) return false;
    char value = (char)('0' + chapter);
    SceUID fd = sceIoOpen(NEXT_CHAPTER_PATH, SCE_O_WRONLY | SCE_O_CREAT | SCE_O_TRUNC, 0666);
    if (fd < 0) return false;
    bool written = sceIoWrite(fd, &value, 1) == 1;
    sceIoClose(fd);
    if (!written) return false;
    char line[80];
    snprintf(line, sizeof(line), "GAME_CHANGE=loadexec chapter=%d", chapter);
    log_line(line);
    int result = sceAppMgrLoadExec("app0:eboot.bin", NULL, NULL);
    snprintf(line, sizeof(line), "GAME_CHANGE=loadexec_returned result=0x%08X", result);
    log_line(line);
    return result >= 0;
}

static int chapter_from_request(const char *working_directory) {
    if (working_directory == NULL) return -1;
    if (strstr(working_directory, "launcher") != NULL) return 0;
    const char *chapter = strstr(working_directory, "chapter");
    if (chapter == NULL) return -1;
    chapter += strlen("chapter");
    return chapter[0] >= '0' && chapter[0] <= '5' ? chapter[0] - '0' : -1;
}

int main(void) {
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);
    sceIoMkdir("ux0:data/deltarune", 0777);
    sceIoMkdir(DATA_ROOT, 0777);
    sceIoMkdir(SAVE_PATH, 0777);
    sceIoRemove(LOG_PATH);
    int active_chapter = consume_next_chapter();

    log_line("Deltarune Windows data + Butterscotch VitaRenderer runner 00.47");
    log_line("MAIN_STACK=4194304");
    char startup_line[96];
    snprintf(startup_line, sizeof(startup_line), "AUDIO=openal ENTRY=chapter%d CONTROLS=vita+touch", active_chapter);
    log_line(startup_line);

    sceCtrlSetSamplingMode(SCE_CTRL_MODE_ANALOG);
    sceTouchSetSamplingState(SCE_TOUCH_PORT_FRONT, SCE_TOUCH_SAMPLING_STATE_START);
    // The generated fixed-pipeline shader used by the legacy renderer trips the
    // aggressive runtime optimizer on Vita. O0 is slower only during the first
    // compilation and avoids that optimizer path entirely.
    vglSetupRuntimeShaderCompiler(SHARK_OPT_SLOW, 0, 0, 0);
    log_line("SHARK=opt_slow fastmath=0 fastprecision=0 fastint=0");
    log_line("RENDERER=vita_arrays_v2 immediate_bridge=all STDIO=unbuffered");
    log_line("VITAGL=init_begin reserve=67108864");
    vglInitExtended(0, 960, 544, 64 * 1024 * 1024, SCE_GXM_MULTISAMPLE_NONE);
    log_line("VITAGL=init_complete");

    VitaSettings settings;
    VitaSettings_load(&settings);
    VitaSettings_setLauncherMode(active_chapter == 0);
    VitaBorders_init(active_chapter);

    int next_chapter = -1;
    char game_path[192];
    char bundle_path[128];
    snprintf(game_path, sizeof(game_path), DATA_ROOT "chapter%d/game.droid", active_chapter);
    snprintf(bundle_path, sizeof(bundle_path), DATA_ROOT "chapter%d/", active_chapter);
    if (settings.ptbrEnabled) {
        SceIoStat mod_stat;
        char mod_game[160];
        snprintf(mod_game, sizeof(mod_game), DATA_ROOT "mods/PTBR/chapter%d/game.droid", active_chapter);
        if (sceIoGetstat(mod_game, &mod_stat) >= 0) {
            snprintf(game_path, sizeof(game_path), "%s", mod_game);
            log_line("MOD=PTBR alternate_game=enabled");
        }
    }

    DataWinParserOptions options = {0};
    options.parseGen8 = true; options.parseOptn = true; options.parseLang = true;
    options.parseExtn = true; options.parseSond = true; options.parseAgrp = true;
    options.parseSprt = true; options.parseBgnd = true; options.parsePath = true;
    options.parseScpt = true; options.parseGlob = true; options.parseShdr = true;
    options.parseFont = true; options.parseTmln = true; options.parseObjt = true;
    options.parseRoom = true; options.parseTpag = true; options.parseCode = true;
    options.parseVari = true; options.parseFunc = true; options.parseStrg = true;
    options.parseTxtr = true; options.parseAudo = true;
    options.skipLoadingPreciseMasksForNonPreciseSprites = true;
    options.lazyLoadRooms = true;
    options.lazyLoadTextures = true;
    options.lazyLoadAudio = true;
    options.loadType = DATAWINLOADTYPE_LOAD_PER_CHUNK;
    options.progressCallback = progress;

    log_line("DATAWIN=parse_begin");
    DataWin *dw = DataWin_parse(game_path, options);
    log_line("DATAWIN=parse_complete");
    VMContext *vm = VM_create(dw);
    log_line("VM=create_complete");
    OverlayFileSystem *fs = OverlayFileSystem_create(bundle_path, SAVE_PATH);
    char mod_path[160];
    if (settings.ptbrEnabled && active_chapter > 0) {
        snprintf(mod_path, sizeof(mod_path), DATA_ROOT "mods/PTBR/chapter%d/", active_chapter);
        OverlayFileSystem_setModPath(fs, mod_path);
        log_line("MOD=PTBR overlay=enabled");
    } else {
        log_line("MOD=Original overlay=disabled");
    }
    Renderer *renderer = GLLegacyRenderer_create();
    AudioSystem *audio = (AudioSystem *)AlAudioSystem_create();
    log_line("SUBSYSTEMS=create_complete");

    Runner *runner = Runner_create(dw, vm, renderer, (FileSystem *)fs, audio);
    // The Steam launcher requires the Windows branch to emit game_change for
    // chapter selection. Reporting os_psvita leaves it in PLACE_CHAPTER_SELECT.
    runner->osType = OS_WINDOWS;
    log_line("PLATFORM=os_windows steam_launcher_compatible");
    VitaSettings_applyAudio(&settings, audio);
    char *launcher_args[] = {"eboot.bin", "-game", "data.win"};
    char *chapter_args[] = {"eboot.bin", "-game", "data.win", "launcher", "switch_-1", "returning_0"};
    if (active_chapter == 0) {
        Runner_setGameArgs(runner, launcher_args, 3);
        log_line("ARGS=eboot.bin|-game|data.win");
    } else {
        Runner_setGameArgs(runner, chapter_args, 6);
        log_line("ARGS=eboot.bin|-game|data.win|launcher|switch_-1|returning_0");
    }
    runner->debugMode = false;
    log_line("RUNNER=create_complete");
    Runner_initFirstRoom(runner);
    log_line("RUNNER=first_room_complete");
    char display_line[160];
    snprintf(display_line, sizeof(display_line), "DISPLAY=gen8_%dx%d applied_%dx%d host_960x544 mode=native_centered",
             (int)dw->gen8.defaultWindowWidth, (int)dw->gen8.defaultWindowHeight,
             (int)dw->gen8.defaultWindowWidth, (int)dw->gen8.defaultWindowHeight);
    log_line(display_line);

    bool previous[sizeof(KEY_MAP) / sizeof(KEY_MAP[0])] = {0};
    uint32_t frame = 0;
    uint64_t last_time = sceKernelGetProcessTimeWide();
    uint64_t next_frame_deadline = last_time;
    bool exit_requested = false;
    int logged_game_w = -1;
    int logged_game_h = -1;
    int logged_room_index = -999;
    uint64_t perf_window_start = last_time;
    uint64_t perf_total_us = 0, perf_max_us = 0;
    uint32_t perf_frames = 0, perf_drops = 0, perf_severe = 0;
    uint64_t last_slow_log = 0;
    bool save_load_fade = false;
    uint64_t save_load_fade_start = 0;
    const uint64_t save_load_fade_duration = 1000000ULL;

    while (!exit_requested && !runner->shouldExit) {
        RunnerKeyboard_beginFrame(runner->keyboard);
        RunnerGamepad_beginFrame(runner->gamepads);
        RunnerMouse_beginFrame(runner->mouse);
        SceCtrlData pad = {0};
        sceCtrlPeekBufferPositive(0, &pad, 1);
        bool restart_for_settings = VitaSettings_handleInput(&settings, &pad, audio);
        if (restart_for_settings) {
            int settings_target = settings.returnToChapterSelect ? 0 : active_chapter;
            log_line(settings.returnToChapterSelect ? "SETTINGS=return_to_chapter_select" : "SETTINGS=restart_for_mod");
            if (restart_into_chapter(settings_target)) {
                sceKernelDelayThread(500000);
                sceKernelExitProcess(0);
            }
        }
        int dx = (int)pad.lx - 128, dy = (int)pad.ly - 128;
        SceTouchData touch = {0};
        bool touch_up = false, touch_down = false, touch_left = false, touch_right = false;
        float touch_axis_x = 0.0f, touch_axis_y = 0.0f;
        bool touch_confirm = false, touch_cancel = false, touch_menu = false;
        if (settings.touchEnabled && !settings.open && sceTouchPeek(SCE_TOUCH_PORT_FRONT, &touch, 1) > 0) {
            for (unsigned i = 0; i < touch.reportNum; ++i) {
                int tx = touch.report[i].x;
                int ty = touch.report[i].y;
                if (tx < 960) {
                    int tdx = tx - 310;
                    int tdy = ty - 840;
                    touch_axis_x = (float)tdx / 210.0f;
                    touch_axis_y = (float)tdy / 210.0f;
                    if (abs(tdx) > abs(tdy)) {
                        touch_left |= tdx < -90;
                        touch_right |= tdx > 90;
                    } else {
                        touch_up |= tdy < -90;
                        touch_down |= tdy > 90;
                    }
                } else if (tx >= 1540) {
                    touch_confirm = true;
                } else if (tx >= 1250) {
                    touch_cancel = true;
                } else {
                    touch_menu = true;
                }
            }
        }
        float visual_x = dx < -24 || dx > 24 ? (float)dx / 127.0f : touch_axis_x;
        float visual_y = dy < -24 || dy > 24 ? (float)dy / 127.0f : touch_axis_y;
        VitaSettings_setTouchVisuals(&settings, visual_x, visual_y,
                                     (pad.buttons & SCE_CTRL_CROSS) || touch_confirm,
                                     (pad.buttons & (SCE_CTRL_CIRCLE | SCE_CTRL_SQUARE)) || touch_cancel,
                                     (pad.buttons & SCE_CTRL_TRIANGLE) || touch_menu);
        for (ptrdiff_t i = 0; i < arrlen(runner->instances); ++i) {
            Instance* inst = runner->instances[i];
            if (inst == NULL || inst->objectIndex < 0 || (uint32_t)inst->objectIndex >= dw->objt.count) continue;
            const char* object_name = dw->objt.objects[inst->objectIndex].name;
            if (object_name != NULL && strcmp(object_name, "obj_mobilecontroller") == 0) {
                inst->visible = settings.touchEnabled;
            }
        }

        bool controls_enabled = !settings.open && !settings.adjustMode && settings.inputCooldown == 0;
        set_key(runner->keyboard, VK_UP, controls_enabled && ((pad.buttons & SCE_CTRL_UP) || dy < -48 || touch_up), &previous[0]);
        set_key(runner->keyboard, VK_DOWN, controls_enabled && ((pad.buttons & SCE_CTRL_DOWN) || dy > 48 || touch_down), &previous[1]);
        set_key(runner->keyboard, VK_LEFT, controls_enabled && ((pad.buttons & SCE_CTRL_LEFT) || dx < -48 || touch_left), &previous[2]);
        set_key(runner->keyboard, VK_RIGHT, controls_enabled && ((pad.buttons & SCE_CTRL_RIGHT) || dx > 48 || touch_right), &previous[3]);
        set_key(runner->keyboard, 'Z', controls_enabled && ((pad.buttons & SCE_CTRL_CROSS) || touch_confirm), &previous[4]);
        set_key(runner->keyboard, 'X', controls_enabled && ((pad.buttons & (SCE_CTRL_CIRCLE | SCE_CTRL_SQUARE)) || touch_cancel), &previous[5]);
        set_key(runner->keyboard, 'C', controls_enabled && ((pad.buttons & SCE_CTRL_TRIANGLE) || touch_menu), &previous[7]);
        set_key(runner->keyboard, VK_PAGEDOWN, controls_enabled && (pad.buttons & SCE_CTRL_LTRIGGER), &previous[8]);
        set_key(runner->keyboard, VK_PAGEUP, controls_enabled && (pad.buttons & SCE_CTRL_RTRIGGER), &previous[9]);

        uint64_t frame_begin = sceKernelGetProcessTimeWide();
        uint64_t now = frame_begin;
        runner->deltaTime = (double)(now - last_time);
        last_time = now;
        uint64_t step_begin = sceKernelGetProcessTimeWide();
        if (!settings.open && !settings.adjustMode) {
            if (frame == 0) log_line("FRAME0=step_begin");
            Runner_step(runner);
            if (frame == 0) log_line("FRAME0=step_complete");
        }
        uint64_t step_us = sceKernelGetProcessTimeWide() - step_begin;
        if (runner->pendingWorkingDirectory != NULL) {
            int requested_chapter = chapter_from_request(runner->pendingWorkingDirectory);
            char line[160];
            snprintf(line, sizeof(line), "GAME_CHANGE=request cwd=%s params=%s parsed=%d",
                     runner->pendingWorkingDirectory,
                     runner->pendingLaunchParameters ? runner->pendingLaunchParameters : "<null>",
                     requested_chapter);
            log_line(line);
            if (requested_chapter >= 0 && requested_chapter <= 5) {
                next_chapter = requested_chapter;
                if (restart_into_chapter(next_chapter)) {
                    sceKernelDelayThread(500000);
                    sceKernelExitProcess(0);
                }
                log_line("GAME_CHANGE=loadexec_failed");
            } else if (active_chapter > 0) {
                next_chapter = 0;
                log_line("GAME_CHANGE=chapter_select_fallback_launcher");
                if (restart_into_chapter(0)) {
                    sceKernelDelayThread(500000);
                    sceKernelExitProcess(0);
                }
                log_line("GAME_CHANGE=launcher_loadexec_failed");
            } else log_line("GAME_CHANGE=invalid_chapter");
            exit_requested = true;
            continue;
        }
        uint64_t audio_begin = sceKernelGetProcessTimeWide();
        runner->audioSystem->vtable->update(runner->audioSystem, (float)(runner->deltaTime / 1000000.0));
        uint64_t audio_us = sceKernelGetProcessTimeWide() - audio_begin;

        uint64_t render_begin = sceKernelGetProcessTimeWide();
        glClearColor(0, 0, 0, 1);
        glClear(GL_COLOR_BUFFER_BIT);
        int game_w = runner->applicationWidth > 0 ? runner->applicationWidth : (int)dw->gen8.defaultWindowWidth;
        int game_h = runner->applicationHeight > 0 ? runner->applicationHeight : (int)dw->gen8.defaultWindowHeight;
        runner->widescreenExtraWidth = 0;
        runner->widescreenExtraHeight = 0;
        if (game_w != logged_game_w || game_h != logged_game_h) {
            char runtime_display[128];
            snprintf(runtime_display, sizeof(runtime_display),
                     "DISPLAY=runtime_%dx%d host_960x544 centered", game_w, game_h);
            log_line(runtime_display);
            logged_game_w = game_w;
            logged_game_h = game_h;
        }
        if (frame == 0) log_line("FRAME0=draw_pre_begin");
        Runner_drawPre(runner, 960, 544);
        if (frame == 0) log_line("FRAME0=draw_pre_complete");
        Runner_beginFrame(runner, game_w, game_h, 960, 544, 960, 544);
        if (frame == 0) log_line("FRAME0=begin_frame_complete");
        Runner_drawViews(runner, game_w, game_h, false);
        if (frame == 0) log_line("FRAME0=draw_views_complete");
        VitaBorders_updateRoom(runner->currentRoom != NULL ? runner->currentRoom->name : NULL);
        VitaBorders_draw(960, 544);
        renderer->vtable->endFrameInit(renderer);
        if (frame == 0) log_line("FRAME0=end_frame_init_complete");
        if (frame == 0) log_line("FRAME0=draw_post_begin");
        Runner_drawPost(runner, 960, 544);
        if (frame == 0) log_line("FRAME0=draw_post_complete");
        renderer->vtable->endFrameEnd(renderer);
        if (frame == 0) log_line("FRAME0=end_frame_end_complete");
        Runner_drawGUI(runner, 960, 544, game_w, game_h);
        if (frame == 0) log_line("FRAME0=draw_gui_complete");
        VitaSettings_drawTouchControls(&settings, renderer);
        if (frame == 0) log_line("FRAME0=touch_overlay_complete");
        VitaSettings_draw(&settings, renderer);
        if (frame == 0) log_line("FRAME0=settings_overlay_complete");
        VitaSettings_drawCalibration(&settings, renderer);
        if (frame == 0) log_line("FRAME0=calibration_overlay_complete");
        if (save_load_fade) {
            uint64_t fade_now = sceKernelGetProcessTimeWide();
            uint64_t elapsed = fade_now - save_load_fade_start;
            float progress = (float)elapsed / (float)save_load_fade_duration;
            if (progress >= 1.0f) {
                progress = 1.0f;
                save_load_fade = false;
                log_line("SAVE_LOAD_FADE=complete");
            }
            AlAudioSystem_setCategoryGains((AlAudioSystem*)audio,
                ((float)settings.musicVolume / 10.0f) * progress,
                (float)settings.sfxVolume / 10.0f);
            if (progress < 1.0f) {
                renderer->vtable->drawRectangle(renderer, 0.0f, 0.0f, 960.0f, 544.0f,
                                                 0x000000, 1.0f - progress, false);
            }
        }
        if (runner->pendingRoom == -1) {
            if (frame == 0) log_line("FRAME0=swap_begin");
            vglSwapBuffers(settings.vsyncEnabled ? GL_TRUE : GL_FALSE);
            if (frame == 0) log_line("FRAME0=swap_complete");
        }
        const char* previous_room_name = runner->currentRoom != NULL ? runner->currentRoom->name : NULL;
        bool leaving_save_menu = previous_room_name != NULL &&
            (strcmp(previous_room_name, "PLACE_MENU") == 0 ||
             strstr(previous_room_name, "PLACE_MENU") != NULL);
        int room_before_pending = runner->currentRoomIndex;
        Runner_handlePendingRoomChange(runner);
        if (active_chapter > 0 && leaving_save_menu && runner->currentRoomIndex != room_before_pending) {
            save_load_fade = true;
            save_load_fade_start = sceKernelGetProcessTimeWide();
            AlAudioSystem_setCategoryGains((AlAudioSystem*)audio, 0.0f,
                                           (float)settings.sfxVolume / 10.0f);
            log_line("SAVE_LOAD_FADE=begin duration_ms=1000");
        }

        uint64_t work_us = sceKernelGetProcessTimeWide() - frame_begin;
        uint64_t render_us = sceKernelGetProcessTimeWide() - render_begin;
        perf_total_us += work_us;
        if (work_us > perf_max_us) perf_max_us = work_us;
        perf_frames++;
        if (work_us > 40000) perf_drops++;
        if (work_us > 80000) perf_severe++;
        if (runner->currentRoomIndex != logged_room_index) {
            char room_change[192];
            snprintf(room_change, sizeof(room_change), "ROOM_CHANGE frame=%u from=%d to=%d name=%s work_us=%llu",
                     frame, logged_room_index, runner->currentRoomIndex,
                     runner->currentRoom && runner->currentRoom->name ? runner->currentRoom->name : "<null>",
                     (unsigned long long)work_us);
            log_line(room_change);
            logged_room_index = runner->currentRoomIndex;
        }
        if (work_us > 50000 && frame_begin - last_slow_log > 1000000ULL) {
            char slow[224];
            snprintf(slow, sizeof(slow), "PERF_SLOW frame=%u total_us=%llu step_us=%llu audio_us=%llu render_us=%llu room=%s index=%d",
                     frame, (unsigned long long)work_us, (unsigned long long)step_us,
                     (unsigned long long)audio_us, (unsigned long long)render_us,
                     runner->currentRoom && runner->currentRoom->name ? runner->currentRoom->name : "<null>",
                     runner->currentRoomIndex);
            log_line(slow);
            last_slow_log = frame_begin;
        }
        if (frame_begin - perf_window_start >= 5000000ULL && perf_frames > 0) {
            char summary[192];
            snprintf(summary, sizeof(summary), "PERF_SUMMARY frames=%u avg_us=%llu max_us=%llu drops40=%u severe80=%u room=%s",
                     perf_frames, (unsigned long long)(perf_total_us / perf_frames),
                     (unsigned long long)perf_max_us, perf_drops, perf_severe,
                     runner->currentRoom && runner->currentRoom->name ? runner->currentRoom->name : "<null>");
            log_line(summary);
            perf_window_start = frame_begin;
            perf_total_us = perf_max_us = 0;
            perf_frames = perf_drops = perf_severe = 0;
        }

        frame++;
        if (frame == 1) log_line("FRAME=first_complete");
        if (frame == 60) {
            char room_line[128];
            snprintf(room_line, sizeof(room_line), "FRAME=60_complete chapter=%d room=%s index=%d",
                     active_chapter,
                     runner->currentRoom && runner->currentRoom->name ? runner->currentRoom->name : "<null>",
                     runner->currentRoomIndex);
            log_line(room_line);
        }
        if (settings.vsyncEnabled) {
            const uint64_t target = 1000000ULL / 30ULL;
            next_frame_deadline += target;
            uint64_t current_time = sceKernelGetProcessTimeWide();
            if (next_frame_deadline > current_time) {
                sceKernelDelayThread((unsigned int)(next_frame_deadline - current_time));
            } else if (current_time - next_frame_deadline > target) {
                next_frame_deadline = current_time;
            }
        } else {
            next_frame_deadline = sceKernelGetProcessTimeWide();
        }
    }

    if (runner->shouldExit && active_chapter > 0) {
        log_line("GAME_CHANGE=game_end_return_to_launcher");
        if (restart_into_chapter(0)) {
            sceKernelDelayThread(500000);
            sceKernelExitProcess(0);
        }
        log_line("GAME_CHANGE=launcher_loadexec_failed");
    }
    log_line(next_chapter >= 0 ? "EXIT=chapter_switch" : "EXIT=runner_requested");
    Runner_free(runner);
    runner = NULL;
    audio->vtable->destroy(audio);
    VitaBorders_shutdown();
    renderer->vtable->destroy(renderer);
    OverlayFileSystem_destroy(fs);
    VM_free(vm);
    DataWin_free(dw);
    log_line("PROCESS=exit_clean");
    sceKernelExitProcess(0);
    return 0;
}
